var baseUrl = 'http://localhost:8000'
var USER_LOGIN = baseUrl + '/admin/login'
var USER_LOGOUT = baseUrl + '/admin/logout'
var USER_INFO = baseUrl + '/admin/getuser'
var user = baseUrl + '/admin/article_count'