var baseUrl = 'http://localhost:8000'
var USER_LOGIN = baseUrl + '/admin/login'
var USER_LOGOUT = baseUrl + '/admin/logout'
var USER_INFO = baseUrl + '/admin/getuser'
var USER_INFO_GET = baseUrl + '/admin/userinfo_get'
var USER_INFO_EDIT = baseUrl + '/admin/userinfo_edit'